version: '3.8'

services:
  image-host:
    build: .
    container_name: simple-image-host
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - ENABLE_AUTH=true
      - AUTH_PASSWORD=your-secure-password-change-me
      - SESSION_SECRET=your-random-session-secret-change-me
      - ALLOW_PERMANENT_STORAGE=false
    volumes:
      - ./uploads:/app/uploads
      - ./database.db:/app/database.db
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/api/auth/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

# 可选：如果需要使用外部数据库，可以添加数据库服务
# services:
#   image-host:
#     # ... 上面的配置
#     depends_on:
#       - db
#   
#   db:
#     image: postgres:15-alpine
#     container_name: image-host-db
#     restart: unless-stopped
#     environment:
#       POSTGRES_DB: imagehost
#       POSTGRES_USER: imagehost
#       POSTGRES_PASSWORD: your-db-password
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     ports:
#       - "5432:5432"
# 
# volumes:
#   postgres_data: 